# Generated by Django 3.2.14 on 2022-08-14 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourney', '0001_initial'),
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', related_query_name='section', to='tourney.tournament'),
        ),
        migrations.AddField(
            model_name='roundsubsection',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', related_query_name='subsection', to='tourney.round'),
        ),
        migrations.AddField(
            model_name='roundsubsection',
            name='subsection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_subsections', related_query_name='round_subsection', to='submission.subsection'),
        ),
        migrations.AddField(
            model_name='captainsmeetingsection',
            name='captains_meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', related_query_name='section', to='tourney.captainsmeeting'),
        ),
        migrations.AddField(
            model_name='captainsmeetingsection',
            name='competitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', related_query_name='role', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeetingsection',
            name='subsection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captains_meetings', related_query_name='captains_meeting', to='submission.subsection'),
        ),
        migrations.AddField(
            model_name='ballotsection',
            name='ballot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', related_query_name='section', to='submission.ballot'),
        ),
        migrations.AddField(
            model_name='ballotsection',
            name='subsection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot_sections', related_query_name='ballot_section', to='submission.subsection'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='att_rank_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_rank_1', related_query_name='att_rank_1', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='att_rank_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_rank_2', related_query_name='att_rank_2', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='att_rank_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_rank_3', related_query_name='att_rank_3', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='att_rank_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_rank_4', related_query_name='att_rank_4', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', related_query_name='ballot', to='tourney.judge'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', related_query_name='ballot', to='tourney.round'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='wit_rank_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wit_rank_1', related_query_name='wit_rank_1', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='wit_rank_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wit_rank_2', related_query_name='wit_rank_2', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='wit_rank_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wit_rank_3', related_query_name='wit_rank_3', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='wit_rank_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wit_rank_4', related_query_name='wit_rank_4', to='tourney.competitor'),
        ),
        migrations.AlterUniqueTogether(
            name='ballot',
            unique_together={('round', 'judge')},
        ),
    ]
