# Generated by Django 3.2.14 on 2022-08-15 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0001_initial'),
        ('submission', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptainsMeeting',
            fields=[
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='captains_meeting', related_query_name='captains_meeting', serialize=False, to='tourney.round')),
                ('character_evidence_option1', models.BooleanField(default=False, help_text='The defendant will offer evidence under MRE 404(a)(1) of the following traits of his/her own character:')),
                ('character_evidence_option1_description', models.CharField(default='', max_length=40)),
                ('character_evidence_option2', models.BooleanField(default=False, help_text="The defendant will offer evidence under MRE 404(a)(2) of the following traits of the victim(s)' character:")),
                ('character_evidence_option2_description', models.CharField(default='', max_length=40)),
                ('character_evidence_option3', models.BooleanField(default=False, help_text='The prosecutor will offer evidence of prior crimes, wrongs, or acts under MRE 404(b) for the following purposes:')),
                ('character_evidence_option3_description', models.CharField(default='', max_length=40)),
                ('character_evidence_option4', models.BooleanField(default=False, help_text='The defense will attack, by reputation or opinion, credibility of the following witnesses called by the prosecution under MRE 608(a)')),
                ('character_evidence_option4_description', models.CharField(default='', max_length=40)),
                ('character_evidence_submit', models.BooleanField(default=False, help_text='Was Character Evidence form completed?')),
                ('p_charge', models.CharField(choices=[('Haley Floyd', 'Haley Floyd'), ('Winston Thomas', 'Winston Thomas'), ('Both victims', 'Both victims')], max_length=30, null=True)),
                ('d_charge', models.CharField(choices=[('not_guilty', 'Not guilty of all criminal charges.'), ('not_guilty_robbery_1', 'Not guilty of ROBBERY 1 but guilty of ROBBERY 2 and THEFT BY DECEPTION.'), ('not_guilty_robbery', 'Not guilty of ROBBERY but guilty of THEFT BY DECEPTION')], max_length=30, null=True)),
                ('p_wit1_name', models.CharField(choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True)),
                ('p_wit2_name', models.CharField(choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True)),
                ('p_wit3_name', models.CharField(choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True)),
                ('d_wit1_name', models.CharField(choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True)),
                ('d_wit2_name', models.CharField(choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True)),
                ('d_wit3_name', models.CharField(choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True)),
                ('demo', models.BooleanField(default=False, help_text='Were all exhibits/demonstratives shown to opposing counsel?')),
                ('submit', models.BooleanField(default=False, help_text='Submit')),
                ('d_closer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_closer', to='tourney.competitor')),
                ('d_opener', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_opener', to='tourney.competitor')),
                ('d_wit1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit1', to='tourney.competitor')),
                ('d_wit1_cross_att', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit1_cross_att', to='tourney.competitor')),
                ('d_wit1_direct_att', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit1_direct_att', to='tourney.competitor')),
                ('d_wit2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit2', to='tourney.competitor')),
                ('d_wit2_cross_att', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit2_cross_att', to='tourney.competitor')),
                ('d_wit2_direct_att', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit2_direct_att', to='tourney.competitor')),
                ('d_wit3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit3', to='tourney.competitor')),
                ('d_wit3_cross_att', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit3_cross_att', to='tourney.competitor')),
                ('d_wit3_direct_att', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit3_direct_att', to='tourney.competitor')),
                ('p_closer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_closer', to='tourney.competitor')),
                ('p_opener', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_opener', related_query_name='p_opener', to='tourney.competitor')),
                ('p_wit1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit1', to='tourney.competitor')),
                ('p_wit1_cross_att', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit1_cross_att', to='tourney.competitor')),
                ('p_wit1_direct_att', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit1_direct_att', to='tourney.competitor')),
                ('p_wit2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit2', to='tourney.competitor')),
                ('p_wit2_cross_att', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit2_cross_att', to='tourney.competitor')),
                ('p_wit2_direct_att', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit2_direct_att', to='tourney.competitor')),
                ('p_wit3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit3', to='tourney.competitor')),
                ('p_wit3_cross_att', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit3_cross_att', to='tourney.competitor')),
                ('p_wit3_direct_att', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit3_direct_att', to='tourney.competitor')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('side', models.CharField(choices=[('p', 'P'), ('d', 'D'), ('other', 'Other')], max_length=5, null=True)),
                ('pronouns', models.CharField(choices=[('he', 'He/Him'), ('she', 'She/Her'), ('they', 'They/Them'), ('ze', 'Ze/Hir')], max_length=20, null=True)),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', related_query_name='character', to='tourney.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterPronouns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronouns', models.CharField(choices=[('he', 'He/Him'), ('she', 'She/Her'), ('they', 'They/Them'), ('ze', 'Ze/Hir')], max_length=20, null=True)),
                ('captains_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captains_meetings', related_query_name='captains_meeting', to='submission.captainsmeeting')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', related_query_name='character', to='submission.character')),
            ],
        ),
        migrations.AlterField(
            model_name='captainsmeetingsection',
            name='captains_meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', related_query_name='section', to='submission.captainsmeeting'),
        ),
    ]
