# Generated by Django 3.2.14 on 2022-08-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20220814_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='is_statement',
        ),
        migrations.AddField(
            model_name='section',
            name='label',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='subsection',
            name='label',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='subsection',
            name='subsection_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('cross', 'Cross'), ('statement', 'Statement')], default='direct', max_length=40),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RoundSubSection',
        ),
    ]
