# Generated by Django 3.2.14 on 2022-08-15 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20220814_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='label',
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='label',
        ),
    ]
