# Generated by Django 3.2.14 on 2022-08-15 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_auto_20220814_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsection',
            old_name='subsection_type',
            new_name='type',
        ),
    ]
