# Generated by Django 3.2.14 on 2022-09-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_rename_subsection_type_subsection_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='pronouns',
        ),
    ]
