# Generated by Django 3.2.14 on 2022-09-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0009_paradigm_paradigmpreference_paradigmpreferenceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradigm',
            name='experience_description',
            field=models.CharField(choices=[('hs', 'I am a former High School Mock Trial Competitor'), ('college', 'I am a current or former College Mock Trial Competitor'), ('ls', 'I am a current or former Law School Mock Trial Competitor')], help_text='Do you have any experience competing in high school, collegiate or law school mock trial competitions?', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='paradigm',
            name='judged_rounds',
            field=models.IntegerField(choices=[(1, 'I have judged 1-2 Mock Trial Competitions in the past'), (2, 'I have judged 3-5 Mock Trial Competitions in the past'), (3, 'I have judged 5 or more Mock Trial Competitions in the past')], help_text='Do you have any experience judging high school, collegiate or law school mock trial competitions?', null=True),
        ),
    ]
