# Generated by Django 3.2.14 on 2022-09-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0010_auto_20220907_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradigm',
            name='experience_years',
            field=models.DecimalField(decimal_places=1, default=0, help_text='How many years of mock trial experience do you have?', max_digits=3),
        ),
    ]
