# Generated by Django 3.2.14 on 2022-09-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0011_alter_paradigm_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterpronouns',
            name='pronouns',
            field=models.CharField(choices=[('he', 'he/him'), ('she', 'she/her'), ('they', 'they/them'), ('ze', 'ze/hir')], max_length=20, null=True),
        ),
    ]
