# Generated by Django 3.2.14 on 2022-09-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0012_alter_characterpronouns_pronouns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='side',
            field=models.CharField(choices=[('P', 'P'), ('D', 'D'), ('other', 'Other')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='side',
            field=models.CharField(choices=[('P', 'P'), ('D', 'D')], max_length=40),
        ),
    ]
