# Generated by Django 3.2.14 on 2022-09-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0013_auto_20220910_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='help_text',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
