# Generated by Django 3.2.14 on 2022-09-13 03:37

import array_field_select.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0014_subsection_help_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paradigm',
            name='judged_rounds',
        ),
        migrations.AlterField(
            model_name='paradigm',
            name='affiliations',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='paradigm',
            name='experience_description',
            field=array_field_select.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('hs', 'I am a former High School Mock Trial Competitor'), ('college', 'I am a current or former College Mock Trial Competitor'), ('ls', 'I am a current or former Law School Mock Trial Competitor'), ('judged', 'I have judged 1-2 Mock Trial Competitions in the past'), ('judged_some', 'I have judged 3-5 Mock Trial Competitions in the past'), ('judged_many', 'I have judged 5 or more Mock Trial Competitions in the past')], help_text='Do you have any experience competing or judging in high school, collegiate or law school mock trial competitions?', max_length=40, null=True), blank=True, null=True, size=6),
        ),
    ]
