# Generated by Django 3.2.14 on 2022-10-06 20:01

import array_field_select.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0015_auto_20220912_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradigm',
            name='experience_description',
            field=array_field_select.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('hs', 'I am a former high school mock trial competitor.'), ('college', 'I am a current or former college mock trial competitor.'), ('ls', 'I am a current or former law school mock trial Competitor.'), ('judged', 'I have judged 1-2 mock trial competitions in the past.'), ('judged_some', 'I have judged 3-5 mock trial competitions in the past.'), ('judged_many', 'I have judged five or more mock trial competitions in the past.')], help_text='Do you have any experience competing or judging in high school, collegiate or law school mock trial competitions?', max_length=40, null=True), blank=True, null=True, size=6),
        ),
    ]
