# Generated by Django 3.2.14 on 2022-11-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0016_alter_paradigm_experience_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='character',
            name='last_name',
        ),
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
