# Generated by Django 3.2.14 on 2022-11-19 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0017_auto_20221115_2115'),
        ('submission', '0017_auto_20221115_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='att_rank_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='att_rank_1', related_query_name='att_rank_1', to='tourney.competitor'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='att_rank_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='att_rank_2', related_query_name='att_rank_2', to='tourney.competitor'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='att_rank_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='att_rank_3', related_query_name='att_rank_3', to='tourney.competitor'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='att_rank_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='att_rank_4', related_query_name='att_rank_4', to='tourney.competitor'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='wit_rank_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wit_rank_1', related_query_name='wit_rank_1', to='tourney.competitor'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='wit_rank_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wit_rank_2', related_query_name='wit_rank_2', to='tourney.competitor'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='wit_rank_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wit_rank_3', related_query_name='wit_rank_3', to='tourney.competitor'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='wit_rank_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wit_rank_4', related_query_name='wit_rank_4', to='tourney.competitor'),
        ),
    ]
