# Generated by Django 3.2.14 on 2022-12-13 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0019_auto_20221213_1338'),
        ('submission', '0018_auto_20221119_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paradigmpreference',
            name='tournament',
        ),
        migrations.AlterField(
            model_name='captainsmeetingsection',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='round_characters', related_query_name='round_character', to='submission.character'),
        ),
        migrations.AlterField(
            model_name='captainsmeetingsection',
            name='competitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', related_query_name='role', to='tourney.competitor'),
        ),
    ]
