# Generated by Django 3.2.14 on 2023-07-21 14:36

from django.db import migrations, models
import submission.models.ballot


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0019_auto_20221213_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='upload',
            field=models.FileField(null=True, upload_to=submission.models.ballot.user_directory_path),
        ),
    ]
