# Generated by Django 3.2.14 on 2023-08-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0021_spirit'),
    ]

    operations = [
        migrations.AddField(
            model_name='spirit',
            name='submit',
            field=models.BooleanField(default=False, help_text='Submit'),
        ),
    ]
