# Generated by Django 3.2.14 on 2023-09-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0027_alter_character_side'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spirit',
            name='round4',
        ),
    ]
