# Generated by Django 3.2.14 on 2022-07-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_members',
        ),
        migrations.AlterField(
            model_name='team',
            name='school',
            field=models.CharField(default='placeholder', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='PPMT Team', max_length=100),
        ),
    ]
