# Generated by Django 3.2.14 on 2022-07-31 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220726_0155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tab',
        ),
    ]
