# Generated by Django 3.2.14 on 2022-07-20 00:56

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220719_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_roster',
            field=accounts.models.ChoiceArrayField(base_field=models.CharField(max_length=100), null=True, size=10),
        ),
    ]
