# Generated by Django 3.2.14 on 2022-09-08 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0006_auto_20220907_2215'),
        ('accounts', '0003_delete_tab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_tab',
        ),
        migrations.AddField(
            model_name='user',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', related_query_name='user', to='tourney.tournament'),
        ),
    ]
