# Generated by Django 3.2.14 on 2022-07-21 00:40

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220719_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_judge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='is_team',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='sides',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(choices=[('P', 'Prosecution'), ('D', 'Defense')], max_length=1), blank=True, null=True, size=4),
        ),
    ]
