# Generated by Django 3.2.14 on 2022-07-21 04:35

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220720_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='judge', serialize=False, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='team', serialize=False, to='accounts.user')),
                ('team_name', models.CharField(default='PPMT Team', max_length=100, null=True)),
                ('division', models.CharField(choices=[('div_1', 'Disney'), ('div_2', 'Universal')], max_length=100, null=True)),
                ('school', models.CharField(default='placeholder', max_length=100, null=True)),
                ('team_roster', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=10)),
                ('sides', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(choices=[('P', 'Prosecution'), ('D', 'Defense')], max_length=1), blank=True, null=True, size=4)),
                ('ballots', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('cs', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('pd', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='ballots',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='division',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pd',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sides',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team_roster',
        ),
    ]
