# Generated by Django 3.2.14 on 2022-07-21 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220720_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tab', serialize=False, to='accounts.user')),
            ],
        ),
    ]
