# Generated by Django 3.2.14 on 2022-07-21 05:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0003_auto_20220720_2257'),
        ('accounts', '0008_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='conflicts',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=40),
        ),
        migrations.AddField(
            model_name='judge',
            name='judge_friends',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), null=True, size=40),
        ),
        migrations.AddField(
            model_name='judge',
            name='judged_round_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot1', to='tourney.ballot'),
        ),
        migrations.AddField(
            model_name='judge',
            name='judged_round_2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot2', to='tourney.ballot'),
        ),
        migrations.AddField(
            model_name='judge',
            name='judged_round_3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot3', to='tourney.ballot'),
        ),
        migrations.AddField(
            model_name='judge',
            name='judged_round_4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot4', to='tourney.ballot'),
        ),
        migrations.AddField(
            model_name='tab',
            name='available_rounds',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.RemoveField(
            model_name='team',
            name='ballots',
        ),
        migrations.AddField(
            model_name='team',
            name='ballots',
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True), blank=True,
                null=True, size=4),
        ),

        migrations.RemoveField(
            model_name='team',
            name='cs',
        ),
        migrations.AddField(
            model_name='team',
            name='cs',
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True), blank=True,
                null=True, size=4),
        ),
        migrations.RemoveField(
            model_name='team',
            name='pd',
        ),
        migrations.AddField(
            model_name='team',
            name='pd',
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=4),
        ),
    ]
