# Generated by Django 3.2.14 on 2022-07-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220720_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.IntegerField(default=0, help_text='enter integer only', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
