# Generated by Django 3.2.14 on 2022-07-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_team_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(choices=[('Disney', 'Disney'), ('Universal', 'Universal')], max_length=100, null=True),
        ),
    ]
