# Generated by Django 3.2.14 on 2022-07-22 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0005_auto_20220721_1819'),
        ('accounts', '0013_auto_20220721_1819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
