# Generated by Django 3.2.14 on 2022-07-25 08:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='judge', serialize=False, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('division', models.CharField(choices=[('Disney', 'Disney'), ('Universal', 'Universal')], max_length=100)),
                ('round_num', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(help_text='enter integer only', primary_key=True, serialize=False)),
                ('team_name', models.CharField(default='PPMT Team', max_length=100, null=True)),
                ('division', models.CharField(choices=[('Disney', 'Disney'), ('Universal', 'Universal')], max_length=100, null=True)),
                ('school', models.CharField(default='placeholder', max_length=100, null=True)),
                ('team_roster', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=10)),
                ('sides', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(choices=[('P', 'Prosecution'), ('D', 'Defense')], max_length=1), blank=True, null=True, size=4)),
                ('cs', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True), blank=True, null=True, size=4)),
                ('pd', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=4)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courtroom', models.CharField(max_length=1, null=True)),
                ('d_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_teams', related_query_name='d_team', to='tourney.team')),
                ('judge_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pairing1s', related_query_name='pairing1', to='tourney.judge')),
                ('judge_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pairing2s', related_query_name='pairing2', to='tourney.judge')),
                ('p_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_teams', related_query_name='p_team', to='tourney.team')),
                ('pairing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', related_query_name='round', to='tourney.pairing')),
            ],
        ),
        migrations.AddField(
            model_name='judge',
            name='conflicts',
            field=models.ManyToManyField(blank=True, null=True, to='tourney.Team'),
        ),
        migrations.AddField(
            model_name='judge',
            name='judge_friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_tourney_judge_judge_friends_+', to='tourney.Judge'),
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('judge_name', models.CharField(max_length=30, null=True)),
                ('p_open', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_open_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_open', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_open_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit1_wit_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit1_wit_cross', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit1_att_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit1_att_cross', models.IntegerField(help_text='this is for d!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit1_wit_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit1_wit_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit1_att_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit1_att_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit2_wit_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit2_wit_cross', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit2_att_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit2_att_cross', models.IntegerField(help_text='this is for d!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit2_wit_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit2_wit_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit2_att_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit2_att_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit3_wit_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit3_wit_cross', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit3_att_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit3_att_cross', models.IntegerField(help_text='this is for d!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit3_wit_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit3_wit_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit3_att_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit3_att_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit1_wit_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit1_wit_cross', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit1_att_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit1_att_cross', models.IntegerField(help_text='this is for p!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit1_wit_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit1_wit_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit1_att_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit1_att_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit2_wit_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit2_wit_cross', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit2_att_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit2_att_cross', models.IntegerField(help_text='this is for p!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit2_wit_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit2_wit_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit2_att_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit2_att_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit3_wit_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit3_wit_cross', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit3_att_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit3_att_cross', models.IntegerField(help_text='this is for p!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit3_wit_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit3_wit_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit3_att_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit3_att_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_close', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_close_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_close', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_close_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('att_ranks', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=4)),
                ('wit_ranks', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=4)),
                ('round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballots', related_query_name='ballot', to='tourney.round')),
            ],
        ),
    ]
