# Generated by Django 3.2.14 on 2022-08-14 22:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_delete_tab'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='judge', serialize=False, to='accounts.user')),
                ('preside', models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Can if needed')], default=0)),
                ('available_round1', models.BooleanField(default=False)),
                ('available_round2', models.BooleanField(default=False)),
                ('available_round3', models.BooleanField(default=False)),
                ('available_round4', models.BooleanField(default=False)),
                ('available_round5', models.BooleanField(default=False)),
                ('checkin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('Disney', 'Disney'), ('Universal', 'Universal')], max_length=100)),
                ('round_num', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('team_submit', models.BooleanField(default=False)),
                ('final_submit', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('division', 'round_num')},
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courtroom', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('section_nums', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('rank_nums', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('p_choice', models.CharField(choices=[('Prosecution', 'Prosecution'), ('Plaintiff', 'Plaintiff')], max_length=40)),
                ('publish_ballot_scores', models.BooleanField(default=False)),
                ('split_division', models.BooleanField(default=False)),
                ('division_team_num', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='CaptainsMeeting',
            fields=[
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='captains_meeting', related_query_name='captains_meeting', serialize=False, to='tourney.round')),
                ('character_evidence_option1', models.BooleanField(default=False, help_text='The defendant will offer evidence under MRE 404(a)(1) of the following traits of his/her own character:')),
                ('character_evidence_option1_description', models.CharField(default='', max_length=40)),
                ('character_evidence_option2', models.BooleanField(default=False, help_text="The defendant will offer evidence under MRE 404(a)(2) of the following traits of the victim(s)' character:")),
                ('character_evidence_option2_description', models.CharField(default='', max_length=40)),
                ('character_evidence_option3', models.BooleanField(default=False, help_text='The prosecutor will offer evidence of prior crimes, wrongs, or acts under MRE 404(b) for the following purposes:')),
                ('character_evidence_option3_description', models.CharField(default='', max_length=40)),
                ('character_evidence_option4', models.BooleanField(default=False, help_text='The defense will attack, by reputation or opinion, credibility of the following witnesses called by the prosecution under MRE 608(a)')),
                ('character_evidence_option4_description', models.CharField(default='', max_length=40)),
                ('character_evidence_submit', models.BooleanField(default=False, help_text='Was Character Evidence form completed?')),
                ('p_charge', models.CharField(choices=[('Haley Floyd', 'Haley Floyd'), ('Winston Thomas', 'Winston Thomas'), ('Both victims', 'Both victims')], max_length=30, null=True)),
                ('d_charge', models.CharField(choices=[('not_guilty', 'Not guilty of all criminal charges.'), ('not_guilty_robbery_1', 'Not guilty of ROBBERY 1 but guilty of ROBBERY 2 and THEFT BY DECEPTION.'), ('not_guilty_robbery', 'Not guilty of ROBBERY but guilty of THEFT BY DECEPTION')], max_length=30, null=True)),
                ('p_wit1_name', models.CharField(choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True)),
                ('p_wit2_name', models.CharField(choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True)),
                ('p_wit3_name', models.CharField(choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True)),
                ('d_wit1_name', models.CharField(choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True)),
                ('d_wit2_name', models.CharField(choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True)),
                ('d_wit3_name', models.CharField(choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True)),
                ('demo', models.BooleanField(default=False, help_text='Were all exhibits/demonstratives shown to opposing counsel?')),
                ('submit', models.BooleanField(default=False, help_text='Submit')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(help_text='enter integer only', primary_key=True, serialize=False)),
                ('team_name', models.CharField(default='PPMT Team', max_length=100, null=True)),
                ('division', models.CharField(choices=[('Disney', 'Disney'), ('Universal', 'Universal')], max_length=100, null=True)),
                ('school', models.CharField(default='placeholder', max_length=100, null=True)),
                ('sides', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(choices=[('P', 'Prosecution'), ('D', 'Defense')], max_length=1), blank=True, null=True, size=4)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='d_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_rounds', related_query_name='d_round', to='tourney.team'),
        ),
        migrations.AddField(
            model_name='round',
            name='extra_judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_rounds', related_query_name='extra_round', to='tourney.judge'),
        ),
        migrations.AddField(
            model_name='round',
            name='p_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_rounds', related_query_name='p_round', to='tourney.team'),
        ),
        migrations.AddField(
            model_name='round',
            name='pairing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', related_query_name='round', to='tourney.pairing'),
        ),
        migrations.AddField(
            model_name='round',
            name='presiding_judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presiding_rounds', related_query_name='presiding_round', to='tourney.judge'),
        ),
        migrations.AddField(
            model_name='round',
            name='scoring_judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rounds', related_query_name='scoring_round', to='tourney.judge'),
        ),
        migrations.AddField(
            model_name='judge',
            name='conflicts',
            field=models.ManyToManyField(blank=True, to='tourney.Team'),
        ),
        migrations.AddField(
            model_name='judge',
            name='judge_friends',
            field=models.ManyToManyField(blank=True, related_name='_tourney_judge_judge_friends_+', to='tourney.Judge'),
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', related_query_name='member', to='tourney.team')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('side', models.CharField(choices=[('p', 'P'), ('d', 'D'), ('other', 'Other')], max_length=5, null=True)),
                ('pronouns', models.CharField(choices=[('he', 'He/Him'), ('she', 'She/Her'), ('they', 'They/Them'), ('ze', 'Ze/Hir')], max_length=20, null=True)),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', related_query_name='character', to='tourney.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterPronouns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronouns', models.CharField(choices=[('he', 'He/Him'), ('she', 'She/Her'), ('they', 'They/Them'), ('ze', 'Ze/Hir')], max_length=20, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', related_query_name='character', to='tourney.character')),
                ('captains_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captains_meetings', related_query_name='captains_meeting', to='tourney.captainsmeeting')),
            ],
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_closer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_closer', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_opener',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_opener', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit1', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit1_cross_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit1_cross_att', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit1_direct_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit1_direct_att', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit2', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit2_cross_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit2_cross_att', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit2_direct_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit2_direct_att', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit3', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit3_cross_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit3_cross_att', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit3_direct_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit3_direct_att', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='p_closer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_closer', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='p_opener',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_opener', related_query_name='p_opener', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='p_wit1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit1', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='p_wit1_cross_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit1_cross_att', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='p_wit1_direct_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit1_direct_att', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='p_wit2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit2', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='p_wit2_cross_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit2_cross_att', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='p_wit2_direct_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit2_direct_att', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='p_wit3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit3', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='p_wit3_cross_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit3_cross_att', to='tourney.competitor'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='p_wit3_direct_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit3_direct_att', to='tourney.competitor'),
        ),
    ]
