# Generated by Django 3.2.14 on 2022-08-13 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('section_nums', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('p_choice', models.CharField(choices=[('Prosecution', 'Prosecution'), ('Plaintiff', 'Plaintiff')], max_length=40)),
                ('publish_ballot_scores', models.BooleanField(default=False)),
                ('split_division', models.BooleanField(default=False)),
                ('division_team_num', models.IntegerField(default=10)),
            ],
        ),
    ]
