# Generated by Django 3.2.14 on 2022-08-15 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_auto_20220814_2022'),
        ('tourney', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='characterpronouns',
            name='captains_meeting',
        ),
        migrations.RemoveField(
            model_name='characterpronouns',
            name='character',
        ),
        migrations.DeleteModel(
            name='CaptainsMeeting',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='CharacterPronouns',
        ),
    ]
