# Generated by Django 3.1.1 on 2022-07-25 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballot',
            name='judge_name',
        ),
        migrations.RemoveField(
            model_name='round',
            name='judge_1',
        ),
        migrations.RemoveField(
            model_name='round',
            name='judge_2',
        ),
        migrations.AddField(
            model_name='ballot',
            name='judge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ballots', related_query_name='ballot', to='tourney.judge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='judges',
            field=models.ManyToManyField(related_name='rounds', related_query_name='round', through='tourney.Ballot', to='tourney.Judge'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', related_query_name='ballot', to='tourney.round'),
        ),
    ]
