# Generated by Django 3.2.14 on 2022-07-20 23:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourney', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='p_wit1_direct',
        ),
        migrations.RemoveField(
            model_name='round',
            name='p_wit2_direct',
        ),
        migrations.AddField(
            model_name='round',
            name='d_close',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='d_close_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='d_open_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit1_att_cross',
            field=models.IntegerField(help_text='this is for p!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit1_att_cross_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit1_att_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit1_att_direct_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit1_wit_cross',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit1_wit_cross_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit1_wit_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit1_wit_direct_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit2_att_cross',
            field=models.IntegerField(help_text='this is for p!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit2_att_cross_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit2_att_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit2_att_direct_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit2_wit_cross',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit2_wit_cross_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit2_wit_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit2_wit_direct_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit3_att_cross',
            field=models.IntegerField(help_text='this is for p!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit3_att_cross_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit3_att_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit3_att_direct_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit3_wit_cross',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit3_wit_cross_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit3_wit_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='d_wit3_wit_direct_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='p_close',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='p_close_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='p_open_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit1_att_cross',
            field=models.IntegerField(help_text='this is for d!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit1_att_cross_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit1_att_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit1_att_direct_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit1_wit_cross',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit1_wit_cross_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit1_wit_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit1_wit_direct_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit2_att_cross',
            field=models.IntegerField(help_text='this is for d!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit2_att_cross_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit2_att_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit2_att_direct_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit2_wit_cross',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit2_wit_cross_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit2_wit_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit2_wit_direct_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit3_att_cross',
            field=models.IntegerField(help_text='this is for d!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit3_att_cross_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit3_att_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit3_att_direct_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit3_wit_cross',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit3_wit_cross_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit3_wit_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='round',
            name='p_wit3_wit_direct_comment',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='round',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='round',
            name='d_open',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='round',
            name='d_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', related_query_name='team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='round',
            name='p_open',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='round',
            name='p_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
