# Generated by Django 3.2.14 on 2022-07-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0002_alter_ballot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='d_open_comment',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='p_open_comment',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='p_wit1_wit_direct_comment',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
