# Generated by Django 3.2.14 on 2022-07-20 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0002_auto_20220720_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='round',
            new_name='round_num',
        ),
    ]
