# Generated by Django 3.2.14 on 2022-08-13 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0002_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='rank_nums',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='section_nums',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
