# Generated by Django 3.2.14 on 2022-07-22 00:35

import django.core.validators
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_team_division'),
        ('tourney', '0003_auto_20220720_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('round', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('div_1', django_better_admin_arrayfield.models.fields.ArrayField(base_field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=30, null=True), null=True, size=6), blank=True, null=True, size=None)),
                ('div_1_team_1', models.CharField(max_length=30)),
                ('div_2', models.ManyToManyField(related_name='div_2_teams', to='accounts.Team')),
            ],
        ),
    ]
