# Generated by Django 3.2.14 on 2022-07-21 00:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourney', '0003_rename_round_round_round_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courtroom', models.CharField(max_length=1, null=True)),
                ('judge_name', models.CharField(max_length=20)),
                ('round_num', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('p_open', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_open_comment', models.CharField(max_length=5000, null=True)),
                ('d_open', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_open_comment', models.CharField(max_length=5000, null=True)),
                ('p_wit1_wit_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit1_wit_cross', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit1_att_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit1_att_cross', models.IntegerField(help_text='this is for d!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit1_wit_direct_comment', models.CharField(max_length=5000, null=True)),
                ('p_wit1_wit_cross_comment', models.CharField(max_length=5000, null=True)),
                ('p_wit1_att_direct_comment', models.CharField(max_length=5000, null=True)),
                ('p_wit1_att_cross_comment', models.CharField(max_length=5000, null=True)),
                ('p_wit2_wit_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit2_wit_cross', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit2_att_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit2_att_cross', models.IntegerField(help_text='this is for d!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit2_wit_direct_comment', models.CharField(max_length=5000, null=True)),
                ('p_wit2_wit_cross_comment', models.CharField(max_length=5000, null=True)),
                ('p_wit2_att_direct_comment', models.CharField(max_length=5000, null=True)),
                ('p_wit2_att_cross_comment', models.CharField(max_length=5000, null=True)),
                ('p_wit3_wit_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit3_wit_cross', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit3_att_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit3_att_cross', models.IntegerField(help_text='this is for d!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit3_wit_direct_comment', models.CharField(max_length=5000, null=True)),
                ('p_wit3_wit_cross_comment', models.CharField(max_length=5000, null=True)),
                ('p_wit3_att_direct_comment', models.CharField(max_length=5000, null=True)),
                ('p_wit3_att_cross_comment', models.CharField(max_length=5000, null=True)),
                ('d_wit1_wit_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit1_wit_cross', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit1_att_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit1_att_cross', models.IntegerField(help_text='this is for p!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit1_wit_direct_comment', models.CharField(max_length=5000, null=True)),
                ('d_wit1_wit_cross_comment', models.CharField(max_length=5000, null=True)),
                ('d_wit1_att_direct_comment', models.CharField(max_length=5000, null=True)),
                ('d_wit1_att_cross_comment', models.CharField(max_length=5000, null=True)),
                ('d_wit2_wit_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit2_wit_cross', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit2_att_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit2_att_cross', models.IntegerField(help_text='this is for p!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit2_wit_direct_comment', models.CharField(max_length=5000, null=True)),
                ('d_wit2_wit_cross_comment', models.CharField(max_length=5000, null=True)),
                ('d_wit2_att_direct_comment', models.CharField(max_length=5000, null=True)),
                ('d_wit2_att_cross_comment', models.CharField(max_length=5000, null=True)),
                ('d_wit3_wit_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit3_wit_cross', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit3_att_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit3_att_cross', models.IntegerField(help_text='this is for p!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit3_wit_direct_comment', models.CharField(max_length=5000, null=True)),
                ('d_wit3_wit_cross_comment', models.CharField(max_length=5000, null=True)),
                ('d_wit3_att_direct_comment', models.CharField(max_length=5000, null=True)),
                ('d_wit3_att_cross_comment', models.CharField(max_length=5000, null=True)),
                ('p_close', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_close_comment', models.CharField(max_length=5000, null=True)),
                ('d_close', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_close_comment', models.CharField(max_length=5000, null=True)),
                ('att_ranks', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=4)),
                ('wit_ranks', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=4)),
                ('d_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_teams', related_query_name='d_team', to=settings.AUTH_USER_MODEL)),
                ('p_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_teams', related_query_name='p_team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Round',
        ),
    ]
