# Generated by Django 3.2.14 on 2022-08-13 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0003_auto_20220812_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', related_query_name='character', to='tourney.tournament'),
        ),
    ]
