# Generated by Django 3.2.14 on 2022-09-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0003_paradigm_paradigmpreference_paradigmpreferenceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='individual_award_rank_plus_record',
            field=models.BooleanField(default=False),
        ),
    ]
