# Generated by Django 3.2.14 on 2022-07-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0004_auto_20220725_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='round',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
