# Generated by Django 3.2.14 on 2022-09-08 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0005_competitor_pronouns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paradigmpreference',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='paradigmpreferenceitem',
            name='paradigm',
        ),
        migrations.RemoveField(
            model_name='paradigmpreferenceitem',
            name='paradigm_preference',
        ),
        migrations.DeleteModel(
            name='Paradigm',
        ),
        migrations.DeleteModel(
            name='ParadigmPreference',
        ),
        migrations.DeleteModel(
            name='ParadigmPreferenceItem',
        ),
    ]
