# Generated by Django 3.2.14 on 2022-07-26 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0005_auto_20220725_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='cs',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pd',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_roster',
        ),
        migrations.AlterField(
            model_name='round',
            name='d_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_rounds', related_query_name='d_round', to='tourney.team'),
        ),
        migrations.AlterField(
            model_name='round',
            name='p_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_rounds', related_query_name='p_round', to='tourney.team'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', related_query_name='member', to='tourney.team')),
            ],
        ),
    ]
