# Generated by Django 3.2.14 on 2022-07-26 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0006_auto_20220725_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballot',
            name='att_ranks',
        ),
        migrations.RemoveField(
            model_name='ballot',
            name='wit_ranks',
        ),
        migrations.AddField(
            model_name='ballot',
            name='att_rank_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_rank_1', related_query_name='att_rank_1', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='att_rank_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_rank_2', related_query_name='att_rank_2', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='att_rank_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_rank_3', related_query_name='att_rank_3', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='att_rank_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_rank_4', related_query_name='att_rank_4', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='wit_rank_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wit_rank_1', related_query_name='wit_rank_1', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='wit_rank_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wit_rank_2', related_query_name='wit_rank_2', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='wit_rank_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wit_rank_3', related_query_name='wit_rank_3', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='wit_rank_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wit_rank_4', related_query_name='wit_rank_4', to='tourney.teammember'),
        ),
    ]
