# Generated by Django 3.2.14 on 2022-07-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0006_auto_20220721_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='round_num',
        ),
        migrations.AddField(
            model_name='round',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
