# Generated by Django 3.2.14 on 2022-07-22 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0007_auto_20220721_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='ballot_1',
        ),
        migrations.RemoveField(
            model_name='round',
            name='ballot_2',
        ),
        migrations.AddField(
            model_name='pairing',
            name='division',
            field=models.CharField(choices=[('Disney', 'Disney'), ('Universal', 'Universal')], default='Disney', max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='judge',
            name='conflicts',
        ),
        migrations.AddField(
            model_name='judge',
            name='conflicts',
            field=models.ManyToManyField(blank=True, null=True, to='tourney.Team'),
        ),
        migrations.RemoveField(
            model_name='judge',
            name='judge_friends',
        ),
        migrations.AddField(
            model_name='judge',
            name='judge_friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_tourney_judge_judge_friends_+', to='tourney.Judge'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='judged_round_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot1', to='tourney.ballot'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='judged_round_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot2', to='tourney.ballot'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='judged_round_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot3', to='tourney.ballot'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='judged_round_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot4', to='tourney.ballot'),
        ),
        migrations.AlterField(
            model_name='round',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
