# Generated by Django 3.2.14 on 2022-07-27 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0007_auto_20220726_0155'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pairing',
            unique_together={('division', 'round_num')},
        ),
        migrations.CreateModel(
            name='CaptainsMeeting',
            fields=[
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='captains_meeting', serialize=False, to='tourney.round')),
                ('character_evidence', models.BooleanField(default=False, help_text='Was Character Evidence form completed?', null=True)),
                ('p_charge', models.CharField(choices=[('Haley Floyd', 'Haley Floyd'), ('Winston Thomas', 'Winston Thomas'), ('Both victims', 'Both victims')], max_length=30, null=True)),
                ('d_charge', models.CharField(choices=[('not_guilty', 'Not guilty of all criminal charges.'), ('not_guilty_robbery_1', 'Not guilty of ROBBERY 1 but guilty of ROBBERY 2 and THEFT BY DECEPTION.'), ('not_guilty_robbery', 'Not guilty of ROBBERY but guilty of THEFT BY DECEPTION')], max_length=30, null=True)),
                ('p_wit1_name', models.CharField(choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True)),
                ('demo', models.BooleanField(default=False, help_text='Were all exhibits/demonstratives shown to opposing counsel?', null=True)),
                ('submit', models.BooleanField(default=False, help_text='Submit', null=True)),
                ('d_opener', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_opener', to='tourney.teammember')),
                ('p_opener', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_opener', to='tourney.teammember')),
                ('p_wit1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit1', to='tourney.teammember')),
                ('p_wit1_cross_att', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit1_cross_att', to='tourney.teammember')),
                ('p_wit1_direct_att', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit1_direct_att', to='tourney.teammember')),
            ],
        ),
    ]
