# Generated by Django 3.2.14 on 2022-09-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0008_alter_competitor_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='section_nums',
            new_name='wit_nums',
        ),
        migrations.AlterField(
            model_name='competitor',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('he', 'he/him'), ('she', 'she/her'), ('they', 'they/them'), ('ze', 'ze/hir')], max_length=20, null=True),
        ),
    ]
