# Generated by Django 3.2.14 on 2022-07-22 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0008_auto_20220721_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='d_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_teams', related_query_name='d_team', to='tourney.team'),
        ),
        migrations.AlterField(
            model_name='round',
            name='judge_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_1', related_query_name='judge_1', to='tourney.judge'),
        ),
        migrations.AlterField(
            model_name='round',
            name='judge_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_2', related_query_name='judge_2', to='tourney.judge'),
        ),
        migrations.AlterField(
            model_name='round',
            name='p_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_teams', related_query_name='p_team', to='tourney.team'),
        ),
    ]
