# Generated by Django 3.2.14 on 2022-09-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0009_auto_20220910_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='case',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='roe',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='zoom_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
