# Generated by Django 3.2.14 on 2022-07-27 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0009_auto_20220726_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_closer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_closer', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit1', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit1_cross_att',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit1_cross_att', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit1_direct_att',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit1_direct_att', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit1_name',
            field=models.CharField(blank=True, choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit2', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit2_cross_att',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit2_cross_att', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit2_direct_att',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit2_direct_att', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit2_name',
            field=models.CharField(blank=True, choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit3', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit3_cross_att',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit3_cross_att', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit3_direct_att',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit3_direct_att', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='d_wit3_name',
            field=models.CharField(blank=True, choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='p_closer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_closer', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='p_wit2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit2', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='p_wit2_cross_att',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit2_cross_att', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='p_wit2_direct_att',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit2_direct_att', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='p_wit2_name',
            field=models.CharField(blank=True, choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='p_wit3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit3', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='p_wit3_cross_att',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit3_cross_att', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='p_wit3_direct_att',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit3_direct_att', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='p_wit3_name',
            field=models.CharField(blank=True, choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True),
        ),
    ]
