# Generated by Django 3.2.14 on 2022-09-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0010_auto_20220910_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.BigAutoField(help_text='enter integer only', primary_key=True, serialize=False),
        ),
    ]
