# Generated by Django 3.2.14 on 2022-07-27 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0010_auto_20220726_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captainsmeeting',
            name='p_opener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_opener', related_query_name='p_opener', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='round',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='captains_meetings', related_query_name='captains_meeting', serialize=False, to='tourney.round'),
        ),
    ]
