# Generated by Django 3.2.14 on 2022-07-22 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0011_rename_round_pairingitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='judged_round_1',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='judged_round_2',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='judged_round_3',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='judged_round_4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ballots',
        ),
        migrations.AddField(
            model_name='ballot',
            name='d_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_ballots', related_query_name='d_ballot', to='tourney.team'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='p_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_ballots', related_query_name='p_ballot', to='tourney.team'),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballots', related_query_name='ballot', to='tourney.judge'),
        ),
    ]
