# Generated by Django 3.2.14 on 2022-07-27 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0011_auto_20220726_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captainsmeeting',
            name='round',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='captains_meeting', related_query_name='captains_meeting', serialize=False, to='tourney.round'),
        ),
    ]
