# Generated by Django 3.2.14 on 2022-09-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0011_alter_team_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(blank=True, choices=[('Disney', 'Disney'), ('Universal', 'Universal')], max_length=100, null=True),
        ),
    ]
