# Generated by Django 3.2.14 on 2022-09-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0012_alter_team_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='sides',
        ),
        migrations.AddField(
            model_name='tournament',
            name='presiding_judge_script',
            field=models.URLField(blank=True, null=True),
        ),
    ]
