# Generated by Django 3.2.14 on 2022-07-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0012_alter_captainsmeeting_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captainsmeeting',
            name='character_evidence',
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='character_evidence_option1',
            field=models.BooleanField(default=False, help_text='The defendant will offer evidence of his/her own character or trait of character [404(a)(1)].'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='character_evidence_option2',
            field=models.BooleanField(default=False, help_text="The defendant will offer evidence of the victim's character or trait of character [404(a)(2)]."),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='character_evidence_option3',
            field=models.BooleanField(default=False, help_text='The prosecutor will offer evidence of prior crimes, wrongs, or acts [404(b)].'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='character_evidence_option4',
            field=models.BooleanField(default=False, help_text='The defense will offer opinion and/or reputation evidence of character [608(a)].'),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='character_evidence_submit',
            field=models.BooleanField(default=False, help_text='Was Character Evidence form completed?'),
        ),
    ]
