# Generated by Django 3.2.14 on 2022-07-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0013_auto_20220727_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='captainsmeeting',
            name='longstreet_pronoun',
            field=models.CharField(choices=[('he', 'He/Him'), ('she', 'She/Her'), ('they', 'They/Them'), ('ze', 'hir')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='demo',
            field=models.BooleanField(default=False, help_text='Were all exhibits/demonstratives shown to opposing counsel?'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='submit',
            field=models.BooleanField(default=False, help_text='Submit'),
        ),
    ]
