# Generated by Django 3.2.14 on 2022-10-06 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0013_auto_20220916_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='hide_comments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='one_judge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='scoring_judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rounds', related_query_name='scoring_round', to='tourney.judge'),
        ),
    ]
