# Generated by Django 3.2.14 on 2022-07-27 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0014_auto_20220727_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captainsmeeting',
            name='d_charge',
            field=models.CharField(choices=[('not_guilty', 'Not guilty of all criminal charges.'), ('not_guilty_robbery_1', 'Not guilty of ROBBERY 1 but guilty of ROBBERY 2 and THEFT BY DECEPTION.'), ('not_guilty_robbery', 'Not guilty of ROBBERY but guilty of THEFT BY DECEPTION')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='d_closer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_closer', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='d_opener',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_opener', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='d_wit1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit1', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='d_wit1_cross_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit1_cross_att', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='d_wit1_direct_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit1_direct_att', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='d_wit1_name',
            field=models.CharField(choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='d_wit2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit2', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='d_wit2_cross_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit2_cross_att', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='d_wit2_direct_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit2_direct_att', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='d_wit2_name',
            field=models.CharField(choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='d_wit3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit3', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='d_wit3_cross_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit3_cross_att', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='d_wit3_direct_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wit3_direct_att', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='d_wit3_name',
            field=models.CharField(choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='p_charge',
            field=models.CharField(choices=[('Haley Floyd', 'Haley Floyd'), ('Winston Thomas', 'Winston Thomas'), ('Both victims', 'Both victims')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='p_closer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_closer', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='p_opener',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_opener', related_query_name='p_opener', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='p_wit1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit1', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='p_wit1_cross_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit1_cross_att', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='p_wit1_direct_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit1_direct_att', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='p_wit1_name',
            field=models.CharField(choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='p_wit2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit2', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='p_wit2_cross_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit2_cross_att', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='p_wit2_direct_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit2_direct_att', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='p_wit2_name',
            field=models.CharField(choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='p_wit3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit3', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='p_wit3_cross_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit3_cross_att', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='p_wit3_direct_att',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wit3_direct_att', to='tourney.teammember'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='p_wit3_name',
            field=models.CharField(choices=[('J.C. Longstreet', 'J.C. Longstreet'), ('Francis Kimball', 'Francis Kimball'), ('Whit Bowman', 'Whit Bowman'), ('Jackie Hunter', 'Jackie Hunter'), ('Charlie Kaminsky', 'Charlie Kaminsky'), ('Billy Isaacs', 'Billy Isaacs'), ('Haley Floyd', 'Haley Floyd')], max_length=30, null=True),
        ),
    ]
