# Generated by Django 3.2.14 on 2022-10-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0014_auto_20221006_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='conflict_other_side',
            field=models.BooleanField(default=True),
        ),
    ]
