# Generated by Django 3.2.14 on 2022-11-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0015_tournament_conflict_other_side'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='one_judge',
        ),
        migrations.AddField(
            model_name='tournament',
            name='judges',
            field=models.IntegerField(default=2),
        ),
    ]
