# Generated by Django 3.2.14 on 2022-07-25 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0015_auto_20220722_0125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PairingItem',
            new_name='Round',
        ),
        migrations.RemoveField(
            model_name='ballot',
            name='courtroom',
        ),
        migrations.RemoveField(
            model_name='ballot',
            name='d_team',
        ),
        migrations.RemoveField(
            model_name='ballot',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='ballot',
            name='p_team',
        ),
        migrations.RemoveField(
            model_name='ballot',
            name='round_num',
        ),
        migrations.AddField(
            model_name='ballot',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballots', related_query_name='ballot', to='tourney.round'),
        ),
    ]
