# Generated by Django 3.2.14 on 2022-07-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0015_auto_20220727_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='captainsmeeting',
            name='bowman_pronoun',
            field=models.CharField(choices=[('he', 'He/Him'), ('she', 'She/Her'), ('they', 'They/Them'), ('ze', 'Ze/Hir')], help_text='Whit Bowman Pronoun', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='floyd_pronoun',
            field=models.CharField(choices=[('he', 'He/Him'), ('she', 'She/Her'), ('they', 'They/Them'), ('ze', 'Ze/Hir')], help_text='Haley Floyd Pronoun', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='hunter_pronoun',
            field=models.CharField(choices=[('he', 'He/Him'), ('she', 'She/Her'), ('they', 'They/Them'), ('ze', 'Ze/Hir')], help_text='Jackie Hunter Pronoun', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='isaacs_pronoun',
            field=models.CharField(choices=[('he', 'He/Him'), ('she', 'She/Her'), ('they', 'They/Them'), ('ze', 'Ze/Hir')], help_text='Billie Issacs Pronoun', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='kaminsky_pronoun',
            field=models.CharField(choices=[('he', 'He/Him'), ('she', 'She/Her'), ('they', 'They/Them'), ('ze', 'Ze/Hir')], help_text='Charlie Kaminsky Pronoun', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='kimball_pronoun',
            field=models.CharField(choices=[('he', 'He/Him'), ('she', 'She/Her'), ('they', 'They/Them'), ('ze', 'Ze/Hir')], help_text='Francis Kimball Pronoun', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='poole_pronoun',
            field=models.CharField(choices=[('he', 'He/Him'), ('she', 'She/Her'), ('they', 'They/Them'), ('ze', 'Ze/Hir')], help_text='Cameron Poole Pronoun', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='longstreet_pronoun',
            field=models.CharField(choices=[('he', 'He/Him'), ('she', 'She/Her'), ('they', 'They/Them'), ('ze', 'Ze/Hir')], help_text='J.C. Longstreet Pronoun', max_length=30, null=True),
        ),
    ]
