# Generated by Django 3.2.14 on 2022-07-27 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0016_auto_20220727_1552'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='captainsmeeting',
            unique_together={('p_opener', 'p_closer')},
        ),
    ]
