# Generated by Django 3.2.14 on 2022-11-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0017_auto_20221115_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='byebuster',
            field=models.BooleanField(default=False),
        ),
    ]
