# Generated by Django 3.2.14 on 2022-07-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0017_alter_captainsmeeting_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='captainsmeeting',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='captainsmeeting',
            constraint=models.UniqueConstraint(fields=('p_opener', 'p_closer'), name='sameperson'),
        ),
    ]
