# Generated by Django 3.2.14 on 2022-12-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0018_team_byebuster'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='d_ballots',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='p_ballots',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='total_ballots',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='total_cs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='total_pd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='publish_ballot_scores',
            field=models.BooleanField(default=False, help_text='Do you want to publish scores or just the comments for the ballots?'),
        ),
    ]
