# Generated by Django 3.2.14 on 2022-07-27 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0018_auto_20220727_1618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='captainsmeeting',
            unique_together={('p_wit1_name', 'p_wit2_name', 'p_wit3_name', 'd_wit1_name', 'd_wit2_name', 'd_wit3_name')},
        ),
    ]
