# Generated by Django 3.2.14 on 2022-12-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0019_auto_20221213_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='d_att',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitor',
            name='d_wit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitor',
            name='p_att',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitor',
            name='p_wit',
            field=models.IntegerField(default=0),
        ),
    ]
