# Generated by Django 3.2.14 on 2022-07-27 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0019_alter_captainsmeeting_unique_together'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='captainsmeeting',
            name='sameperson',
        ),
        migrations.AlterUniqueTogether(
            name='captainsmeeting',
            unique_together=set(),
        ),
    ]
