# Generated by Django 3.2.14 on 2022-07-27 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0020_auto_20220727_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['id']},
        ),
    ]
