# Generated by Django 3.2.14 on 2023-07-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0021_auto_20230118_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
