# Generated by Django 3.2.14 on 2022-07-28 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0022_auto_20220727_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='judges',
        ),
        migrations.AddField(
            model_name='round',
            name='presiding_judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presiding_rounds', related_query_name='presiding_round', to='tourney.judge'),
        ),
        migrations.AddField(
            model_name='round',
            name='scoring_judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rounds', related_query_name='scoring_round', to='tourney.judge'),
        ),
    ]
