# Generated by Django 3.2.14 on 2023-08-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0023_tournament_spirit_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='spirit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='publish_ballot_scores',
            field=models.BooleanField(default=False, help_text='Do you want to publish ballot scores or just comments?'),
        ),
    ]
