# Generated by Django 3.2.14 on 2022-07-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0023_auto_20220727_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='presiding',
            field=models.BooleanField(default=False),
        ),
    ]
