# Generated by Django 3.2.14 on 2022-07-28 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0024_ballot_presiding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballot',
            name='presiding',
        ),
        migrations.AddField(
            model_name='round',
            name='extra_judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_rounds', related_query_name='extra_round', to='tourney.judge'),
        ),
    ]
