# Generated by Django 3.2.14 on 2023-08-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0024_auto_20230803_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='spirit',
            new_name='spirit_score',
        ),
    ]
