# Generated by Django 3.2.14 on 2022-07-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0025_auto_20220727_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='preside',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('CIN', 'Can if needed')], default='N', max_length=30),
        ),
    ]
