# Generated by Django 3.2.14 on 2023-08-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0025_rename_spirit_team_spirit_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='spirit_award',
            new_name='spirit',
        ),
        migrations.AddField(
            model_name='tournament',
            name='hide_captains_meeting',
            field=models.BooleanField(default=False, help_text='Hide the captains meeting?'),
        ),
    ]
