# Generated by Django 3.2.14 on 2023-09-11 03:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0027_tournament_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='short_name',
            field=models.CharField(help_text='Shortened Tournament Name:', max_length=10, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_-]+$', 'You can only enter alphanumerics')]),
        ),
    ]
