# Generated by Django 3.2.14 on 2022-07-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0027_alter_judge_preside'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='preside',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Can if needed')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='ballot',
            unique_together=set(),
        ),
    ]
