# Generated by Django 3.2.14 on 2023-09-11 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0028_alter_tournament_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='short_name',
            field=models.CharField(help_text='Shortened Tournament Name:', max_length=10, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_-]+$', 'You can only enter alphanumerics, underscores, and dashes.')]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='spirit',
            field=models.BooleanField(default=False, help_text='Do you want to enable the spirit award functionality?'),
        ),
    ]
