# Generated by Django 3.2.14 on 2022-07-28 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0028_auto_20220727_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='captainsmeeting',
            name='character_evidence_option1_description',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='character_evidence_option2_description',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='character_evidence_option3_description',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='captainsmeeting',
            name='character_evidence_option4_description',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='d_close',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='d_open',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='d_wit1_att_cross',
            field=models.IntegerField(help_text='this is for p!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='d_wit1_att_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='d_wit1_wit_cross',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='d_wit1_wit_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='d_wit2_att_cross',
            field=models.IntegerField(help_text='this is for p!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='d_wit2_att_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='d_wit2_wit_cross',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='d_wit2_wit_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='d_wit3_att_cross',
            field=models.IntegerField(help_text='this is for p!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='d_wit3_att_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='d_wit3_wit_cross',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='d_wit3_wit_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='p_close',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='p_open',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='p_wit1_att_cross',
            field=models.IntegerField(help_text='this is for d!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='p_wit1_att_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='p_wit1_wit_cross',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='p_wit1_wit_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='p_wit2_att_cross',
            field=models.IntegerField(help_text='this is for d!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='p_wit2_att_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='p_wit2_wit_cross',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='p_wit2_wit_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='p_wit3_att_cross',
            field=models.IntegerField(help_text='this is for d!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='p_wit3_att_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='p_wit3_wit_cross',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='p_wit3_wit_direct',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='character_evidence_option1',
            field=models.BooleanField(default=False, help_text='The defendant will offer evidence under MRE 404(a)(1) of the following traits of his/her own character:'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='character_evidence_option2',
            field=models.BooleanField(default=False, help_text="The defendant will offer evidence under MRE 404(a)(2) of the following traits of the victim(s)' character:"),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='character_evidence_option3',
            field=models.BooleanField(default=False, help_text='The prosecutor will offer evidence of prior crimes, wrongs, or acts under MRE 404(b) for the following purposes:'),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='character_evidence_option4',
            field=models.BooleanField(default=False, help_text='The defense will attack, by reputation or opinion, credibility of the following witnesses called by the prosecution under MRE 608(a)'),
        ),
    ]
