# Generated by Django 3.2.14 on 2023-10-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0029_auto_20230910_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='hide_comments',
            field=models.BooleanField(default=False, help_text='Do you want to hide comments on ballots?'),
        ),
    ]
