# Generated by Django 3.2.14 on 2022-07-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0030_auto_20220728_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captainsmeeting',
            name='character_evidence_option1_description',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='character_evidence_option2_description',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='character_evidence_option3_description',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='captainsmeeting',
            name='character_evidence_option4_description',
            field=models.CharField(default='', max_length=40),
        ),
    ]
