# Generated by Django 3.2.14 on 2022-07-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0031_auto_20220728_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='available_round1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='judge',
            name='available_round2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='judge',
            name='available_round3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='judge',
            name='available_round4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='judge',
            name='available_round5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='ballot',
            unique_together={('round', 'judge')},
        ),
    ]
