# Generated by Django 3.2.14 on 2022-07-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0032_auto_20220728_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairing',
            name='submit',
            field=models.BooleanField(default=False),
        ),
    ]
