# Generated by Django 3.2.14 on 2022-07-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0033_pairing_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='submit',
            field=models.BooleanField(default=False),
        ),
    ]
