# Generated by Django 3.2.14 on 2022-07-30 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0035_auto_20220729_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='submit',
        ),
    ]
