# Generated by Django 3.2.14 on 2022-08-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0037_auto_20220731_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairing',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
