# Generated by Django 3.2.14 on 2022-08-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0038_pairing_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='checkin',
            field=models.BooleanField(default=False),
        ),
    ]
