# Generated by Django 3.2.14 on 2022-08-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0039_judge_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='judge_panel',
            field=models.ManyToManyField(blank=True, null=True, related_name='final_rounds', related_query_name='final_round', to='tourney.Judge'),
        ),
    ]
