# Generated by Django 3.2.14 on 2022-08-13 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_open', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_open_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_open', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_open_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit1_wit_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit1_wit_cross', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit1_att_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit1_att_cross', models.IntegerField(help_text='this is for d!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit1_wit_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit1_wit_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit1_att_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit1_att_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit2_wit_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit2_wit_cross', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit2_att_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit2_att_cross', models.IntegerField(help_text='this is for d!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit2_wit_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit2_wit_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit2_att_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit2_att_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit3_wit_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit3_wit_cross', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit3_att_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit3_att_cross', models.IntegerField(help_text='this is for d!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_wit3_wit_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit3_wit_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit3_att_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_wit3_att_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit1_wit_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit1_wit_cross', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit1_att_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit1_att_cross', models.IntegerField(help_text='this is for p!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit1_wit_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit1_wit_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit1_att_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit1_att_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit2_wit_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit2_wit_cross', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit2_att_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit2_att_cross', models.IntegerField(help_text='this is for p!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit2_wit_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit2_wit_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit2_att_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit2_att_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit3_wit_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit3_wit_cross', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit3_att_direct', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit3_att_cross', models.IntegerField(help_text='this is for p!', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_wit3_wit_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit3_wit_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit3_att_direct_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_wit3_att_cross_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('p_close', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('p_close_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('d_close', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('d_close_comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('submit', models.BooleanField(default=False, help_text='Submit')),
            ],
        ),
    ]
