# Generated by Django 3.2.14 on 2022-08-13 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ballot', '0001_initial'),
        ('tourney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='att_rank_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_rank_1', related_query_name='att_rank_1', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='att_rank_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_rank_2', related_query_name='att_rank_2', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='att_rank_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_rank_3', related_query_name='att_rank_3', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='att_rank_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_rank_4', related_query_name='att_rank_4', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', related_query_name='ballot', to='tourney.judge'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', related_query_name='ballot', to='tourney.round'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='wit_rank_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wit_rank_1', related_query_name='wit_rank_1', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='wit_rank_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wit_rank_2', related_query_name='wit_rank_2', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='wit_rank_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wit_rank_3', related_query_name='wit_rank_3', to='tourney.teammember'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='wit_rank_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wit_rank_4', related_query_name='wit_rank_4', to='tourney.teammember'),
        ),
        migrations.AlterUniqueTogether(
            name='ballot',
            unique_together={('round', 'judge')},
        ),
    ]
