# Generated by Django 3.2.14 on 2022-08-13 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0002_tournament'),
        ('ballot', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('side', models.CharField(choices=[('p', 'Plaintiff'), ('d', 'Defense')], max_length=40)),
                ('role', models.CharField(choices=[('att', 'Attorney'), ('wit', 'Witness')], max_length=40)),
                ('is_statement', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ballot_sections', related_query_name='ballot_section', to='tourney.tournament')),
            ],
        ),
    ]
