# Generated by Django 3.2.14 on 2022-08-13 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0003_auto_20220812_2314'),
        ('ballot', '0004_auto_20220812_2314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoundSection',
            new_name='Section',
        ),
    ]
