# Generated by Django 3.2.14 on 2022-08-13 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0003_auto_20220812_2314'),
        ('ballot', '0005_rename_roundsection_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='is_statement',
        ),
        migrations.RemoveField(
            model_name='section',
            name='role',
        ),
        migrations.RemoveField(
            model_name='section',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='section',
            name='side',
        ),
        migrations.AlterField(
            model_name='section',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', related_query_name='section', to='tourney.tournament'),
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('side', models.CharField(choices=[('p', 'Plaintiff'), ('d', 'Defense')], max_length=40)),
                ('role', models.CharField(choices=[('att', 'Attorney'), ('wit', 'Witness')], max_length=40)),
                ('is_statement', models.BooleanField(default=False)),
                ('sequence', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', related_query_name='subsection', to='tourney.tournament')),
            ],
        ),
        migrations.AlterField(
            model_name='ballotsection',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot_sections', related_query_name='ballot_section', to='ballot.subsection'),
        ),
        migrations.AlterField(
            model_name='captainsmeetingsection',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captains_meetings', related_query_name='captains_meeting', to='ballot.subsection'),
        ),
    ]
