# Generated by Django 3.2.14 on 2022-08-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0007_alter_subsection_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ballotsection',
            old_name='section',
            new_name='subsection',
        ),
        migrations.RenameField(
            model_name='captainsmeetingsection',
            old_name='section',
            new_name='subsection',
        ),
    ]
