# Generated by Django 3.2.14 on 2022-08-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0008_auto_20220812_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsection',
            name='is_statement',
        ),
        migrations.AddField(
            model_name='section',
            name='is_statement',
            field=models.BooleanField(default=False),
        ),
    ]
